"use client";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Eye, EyeOff, LockKeyhole, Sparkles, Zap } from "lucide-react";
import { createClient } from "@/lib/supabase/browser";

export default function SignInPage(){
  const router=useRouter(); const params=useSearchParams(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const {error}=await createClient().auth.signInWithPassword({email,password});if(error)setError(error.message);else{router.push(params.get("next")||"/dashboard");router.refresh()}setLoading(false)}
  return <AuthLayout title="Welcome back" subtitle="Pick up your project exactly where you left off."><form onSubmit={submit} className="auth-form"><label className="label">Email</label><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label className="label">Password</label><div className="password"><input className="input" type={show?"text":"password"} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>{error&&<div className="auth-error">{error}</div>}<button className="btn btn-primary auth-submit" disabled={loading}>{loading?"Signing in…":<>Enter workspace <ArrowRight size={16}/></>}</button><p className="auth-switch">New here? <Link href="/sign-up">Create your account</Link></p></form></AuthLayout>
}
function AuthLayout({children,title,subtitle}:{children:React.ReactNode;title:string;subtitle:string}){return <main className="auth-page"><div className="auth-visual"><div className="auth-brand"><div className="brand-mark"><Zap size={18}/></div><strong>ProjectPilot</strong></div><div><span className="hero-kicker"><Sparkles size={13}/> AI PROJECT OPERATING SYSTEM</span><h1>Turn project chaos into <em>momentum.</em></h1><p>Plan smarter. Build faster. Know what is at risk before your guide does.</p><div className="auth-points"><span>✦ AI planning agents</span><span>✦ Live progress intelligence</span><span>✦ Mentor-grade guidance</span></div></div></div><div className="auth-card"><div className="auth-icon"><LockKeyhole size={19}/></div><h2>{title}</h2><p>{subtitle}</p>{children}</div></main>}
