"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, BrainCircuit, CalendarDays, CheckCircle2, Loader2, Sparkles, Target, WandSparkles } from "lucide-react";
import AppShell from "@/app/components/AppShell";

export default function Planner(){
 const router=useRouter();const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [goal,setGoal]=useState("");const [technology,setTechnology]=useState("");const [deadline,setDeadline]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const r=await fetch("/api/ai/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,description,goal,technology,deadline:deadline||null})});const data=await r.json();if(!r.ok){setError(data.error||"Could not generate the plan.");setLoading(false);return}router.push(`/projects/${data.project.id}`);router.refresh()}
 return <AppShell title="Auto Planner" subtitle="Give the orchestrator one idea. It builds the execution system for you."><div className="planner-layout"><section className="card planner-form fade-up"><div className="planner-title"><div className="ai-spark"><WandSparkles size={19}/></div><div><span className="hero-kicker">MULTI-AGENT ORCHESTRATOR</span><h2>From idea to execution.</h2><p>AI will create your scope, objectives, technology direction, milestones, tasks and risk plan.</p></div></div><form onSubmit={submit} className="planner-fields"><div><label className="label">Project title</label><input className="input" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Smart Lost & Found Platform"/></div><div><label className="label">Describe your idea</label><textarea className="textarea" required value={description} onChange={e=>setDescription(e.target.value)} placeholder="What problem are you solving? Who will use it? What do you imagine building?"/></div><div className="two-col"><div><label className="label">Primary goal <span className="muted">(optional)</span></label><input className="input" value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Reduce response time by…"/></div><div><label className="label">Technology <span className="muted">(optional)</span></label><input className="input" value={technology} onChange={e=>setTechnology(e.target.value)} placeholder="AI will recommend if blank"/></div></div><div><label className="label">Target deadline <span className="muted">(optional)</span></label><input className="input" type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></div>{error&&<div className="auth-error">{error}</div>}<button className="btn btn-primary planner-submit" disabled={loading}>{loading?<><Loader2 size={16} className="spin"/> Orchestrating your project…</>:<><Sparkles size={16}/> Generate complete project <ArrowRight size={16}/></>}</button></form></section><aside className="planner-side"><div className="card agent-stack fade-up delay-1"><span className="hero-kicker">THE AI TEAM</span><Agent icon={<BrainCircuit/>} name="Idea Architect" text="Clarifies the problem and outcome"/><Agent icon={<Target/>} name="Scope Analyst" text="Turns ambition into a buildable scope"/><Agent icon={<Sparkles/>} name="Tech Advisor" text="Chooses a practical technology path"/><Agent icon={<CalendarDays/>} name="Planning Agent" text="Creates milestones and actionable tasks"/><Agent icon={<CheckCircle2/>} name="Risk Predictor" text="Surfaces blockers before they happen"/></div><div className="card planner-note fade-up delay-2"><Sparkles size={18}/><strong>One prompt. A living plan.</strong><span>Everything is saved to your project so the Mentor can reason over the same context later.</span></div></aside></div></AppShell>
}
function Agent({icon,name,text}:{icon:React.ReactNode;name:string;text:string}){return <div className="agent-row"><div className="agent-icon">{icon}</div><div><strong>{name}</strong><span>{text}</span></div><span className="agent-check">✓</span></div>}
